import { TestimonialData } from '../types';

export const mockTestimonial: TestimonialData[] = [
  {
    id: "testimonial-1",
    clientName: "Dr. Sarah Wijaya",
    position: "Dosen",
    institution: "Universitas Indonesia",
    photo: "/images/testimonials/sarah-wijaya.jpg",
    rating: 5,
    testimonialText: "FERAGUIDE benar-benar mengubah cara saya melakukan penelitian. Tim yang profesional dan berpengalaman membantu saya dari proposal hingga berhasil publish di jurnal Q1. Highly recommended!",
    layananDigunakan: ["feraguide", "ferapub"],
    hasilDicapai: "Berhasil publish 2 artikel di jurnal Scopus Q1 dalam 8 bulan",
    status: "aktif",
    featured: true,
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-08-20")
  },
  {
    id: "testimonial-2",
    clientName: "Muhammad Rizki",
    position: "Mahasiswa S2",
    institution: "ITB",
    photo: "/images/testimonials/rizki.jpg",
    rating: 5,
    testimonialText: "Sebagai mahasiswa yang baru pertama kali melakukan riset, FERADATA sangat membantu saya memahami analisis statistik. Penjelasannya mudah dipahami dan hasilnya sangat memuaskan untuk tesis saya.",
    layananDigunakan: ["feradata"],
    hasilDicapai: "Tesis lulus dengan nilai A, hasil analisis dipuji pembimbing",
    status: "aktif",
    featured: true,
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-08-15")
  },
  {
    id: "testimonial-3",
    clientName: "Prof. Dr. Indira Laksmi",
    position: "Profesor",
    institution: "UGM",
    photo: "/images/testimonials/indira-laksmi.jpg",
    rating: 4,
    testimonialText: "FERAGRANT membantu saya menyempurnakan manuscript yang sudah lama tertunda. Editing yang detail dan saran perbaikan yang konstruktif membuat artikel saya diterima di jurnal internasional.",
    layananDigunakan: ["feragrant"],
    hasilDicapai: "Artikel diterima di jurnal international dengan IF 3.2",
    status: "aktif",
    featured: true,
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-08-10")
  },
  {
    id: "testimonial-4",
    clientName: "Andi Setiawan",
    position: "Research Manager",
    institution: "PT Teknologi Maju",
    photo: "/images/testimonials/andi-setiawan.jpg",
    rating: 5,
    testimonialText: "Tim FERADATA sangat profesional dalam menangani data penelitian pasar kami. Insight yang diberikan sangat valuable untuk pengambilan keputusan strategis perusahaan.",
    layananDigunakan: ["feradata", "feragrant"],
    hasilDicapai: "Laporan riset pasar yang comprehensive, ROI meningkat 40%",
    status: "aktif",
    featured: false,
    createdAt: new Date("2024-07-10"),
    updatedAt: new Date("2024-08-05")
  },
  {
    id: "testimonial-5",
    clientName: "Lisa Permata",
    position: "Mahasiswa S3",
    institution: "Unpad",
    photo: "/images/testimonials/lisa-permata.jpg",
    rating: 5,
    testimonialText: "FERAPUB membantu saya navigasi dunia publikasi yang rumit. Berkat bimbingan mereka, saya berhasil publish 3 artikel dalam setahun untuk memenuhi syarat kelulusan doktor.",
    layananDigunakan: ["ferapub", "feragrant"],
    hasilDicapai: "3 publikasi di jurnal Scopus dalam 12 bulan, lulus doktor tepat waktu",
    status: "aktif",
    featured: true,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-25")
  },
  {
    id: "testimonial-6",
    clientName: "Dr. Budi Santoso",
    position: "Peneliti Senior",
    institution: "LIPI",
    photo: "/images/testimonials/budi-santoso.jpg",
    rating: 4,
    testimonialText: "Kualitas layanan Cognifera sangat baik. Tim yang solid dan berpengalaman. Sudah beberapa kali menggunakan jasa mereka dan selalu puas dengan hasilnya.",
    layananDigunakan: ["feraguide", "feradata"],
    hasilDicapai: "Penelitian selesai lebih cepat 30% dari timeline awal",
    status: "aktif",
    featured: false,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-07-15")
  }
];